# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Nombre = QtWidgets.QLabel(self.centralwidget)
        self.label_Nombre.setGeometry(QtCore.QRect(70, 60, 47, 13))
        self.label_Nombre.setObjectName("label_Nombre")
        self.lineEdit_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nombre.setGeometry(QtCore.QRect(230, 60, 181, 20))
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.pushButton_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_guardar.setGeometry(QtCore.QRect(380, 510, 75, 23))
        self.pushButton_guardar.setObjectName("pushButton_guardar")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 510, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_Apellido = QtWidgets.QLabel(self.centralwidget)
        self.label_Apellido.setGeometry(QtCore.QRect(70, 100, 47, 13))
        self.label_Apellido.setObjectName("label_Apellido")
        self.label_Edad = QtWidgets.QLabel(self.centralwidget)
        self.label_Edad.setGeometry(QtCore.QRect(70, 160, 47, 13))
        self.label_Edad.setObjectName("label_Edad")
        self.label_Codigo = QtWidgets.QLabel(self.centralwidget)
        self.label_Codigo.setGeometry(QtCore.QRect(70, 130, 71, 16))
        self.label_Codigo.setObjectName("label_Codigo")
        self.label_Nivel = QtWidgets.QLabel(self.centralwidget)
        self.label_Nivel.setGeometry(QtCore.QRect(70, 190, 47, 13))
        self.label_Nivel.setObjectName("label_Nivel")
        self.label_I = QtWidgets.QLabel(self.centralwidget)
        self.label_I.setGeometry(QtCore.QRect(70, 220, 47, 13))
        self.label_I.setObjectName("label_I")
        self.label_F = QtWidgets.QLabel(self.centralwidget)
        self.label_F.setGeometry(QtCore.QRect(70, 250, 47, 13))
        self.label_F.setObjectName("label_F")
        self.label_Capacidad_Inv = QtWidgets.QLabel(self.centralwidget)
        self.label_Capacidad_Inv.setGeometry(QtCore.QRect(70, 280, 101, 16))
        self.label_Capacidad_Inv.setObjectName("label_Capacidad_Inv")
        self.label_Telefono = QtWidgets.QLabel(self.centralwidget)
        self.label_Telefono.setGeometry(QtCore.QRect(70, 350, 47, 13))
        self.label_Telefono.setObjectName("label_Telefono")
        self.label_Celular = QtWidgets.QLabel(self.centralwidget)
        self.label_Celular.setGeometry(QtCore.QRect(70, 380, 47, 13))
        self.label_Celular.setObjectName("label_Celular")
        self.label_Zona_Res = QtWidgets.QLabel(self.centralwidget)
        self.label_Zona_Res.setGeometry(QtCore.QRect(70, 410, 81, 16))
        self.label_Zona_Res.setObjectName("label_Zona_Res")
        self.label_Oficio = QtWidgets.QLabel(self.centralwidget)
        self.label_Oficio.setGeometry(QtCore.QRect(70, 440, 47, 13))
        self.label_Oficio.setObjectName("label_Oficio")
        self.lineEdit_apellido = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_apellido.setGeometry(QtCore.QRect(230, 90, 181, 20))
        self.lineEdit_apellido.setObjectName("lineEdit_apellido")
        self.lineEdit_dni = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dni.setGeometry(QtCore.QRect(230, 120, 181, 20))
        self.lineEdit_dni.setObjectName("lineEdit_dni")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(230, 150, 181, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_nivel = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nivel.setGeometry(QtCore.QRect(230, 180, 181, 20))
        self.lineEdit_nivel.setObjectName("lineEdit_nivel")
        self.lineEdit_i = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_i.setGeometry(QtCore.QRect(230, 210, 181, 20))
        self.lineEdit_i.setObjectName("lineEdit_i")
        self.lineEdit_f = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_f.setGeometry(QtCore.QRect(230, 240, 181, 20))
        self.lineEdit_f.setObjectName("lineEdit_f")
        self.lineEdit_cap_inv = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cap_inv.setGeometry(QtCore.QRect(230, 270, 181, 20))
        self.lineEdit_cap_inv.setObjectName("lineEdit_cap_inv")
        self.lineEdit_cel = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cel.setGeometry(QtCore.QRect(230, 370, 181, 20))
        self.lineEdit_cel.setObjectName("lineEdit_cel")
        self.lineEdit_telef = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_telef.setGeometry(QtCore.QRect(230, 340, 181, 20))
        self.lineEdit_telef.setObjectName("lineEdit_telef")
        self.lineEdit_dir_domic = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dir_domic.setGeometry(QtCore.QRect(230, 400, 181, 20))
        self.lineEdit_dir_domic.setObjectName("lineEdit_dir_domic")
        self.lineEdit_carr_pro = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_carr_pro.setGeometry(QtCore.QRect(230, 430, 181, 20))
        self.lineEdit_carr_pro.setObjectName("lineEdit_carr_pro")
        self.pushButton_validar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_validar.setGeometry(QtCore.QRect(250, 510, 75, 23))
        self.pushButton_validar.setObjectName("pushButton_validar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Nombre.setText(_translate("MainWindow", "Nombre"))
        self.pushButton_guardar.setText(_translate("MainWindow", "Guardar"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancelar"))
        self.label_Apellido.setText(_translate("MainWindow", "Apellido"))
        self.label_Edad.setText(_translate("MainWindow", "Edad"))
        self.label_Codigo.setText(_translate("MainWindow", "Codigo-DNI"))
        self.label_Nivel.setText(_translate("MainWindow", "Nivel"))
        self.label_I.setText(_translate("MainWindow", "I"))
        self.label_F.setText(_translate("MainWindow", "F"))
        self.label_Capacidad_Inv.setText(_translate("MainWindow", "Capacida Inversion"))
        self.label_Telefono.setText(_translate("MainWindow", "Telefono"))
        self.label_Celular.setText(_translate("MainWindow", "Celular"))
        self.label_Zona_Res.setText(_translate("MainWindow", "Zona Residencia"))
        self.label_Oficio.setText(_translate("MainWindow", "Oficio"))
        self.pushButton_validar.setText(_translate("MainWindow", "Validar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
